version: '2'
services:
    erp-app:
        image: erp
        external_links:
            - erp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/erp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    erp-mysql:
        extends:
            file: mysql.yml
            service: erp-mysql
